In [ ]:
import numpy as np
arr=np.random.randn(5,2)
print(arr)

[[-0.12109372 -0.10762067]
 [-0.78542109 -1.49692817]
 [ 0.73937442  0.6040869 ]
 [ 0.14498344 -1.38157278]
 [-0.08413389 -0.49114499]]


## **Split**

*   In split function the split points that divide the array should mentioned exactly(i.e equla number of split point).




In [ ]:
first,second,third=np.split(arr,[1,3])
print(first,"\n")
print(second,"\n")
print(third)

[[-0.12109372 -0.10762067]] 

[[-0.78542109 -1.49692817]
 [ 0.73937442  0.6040869 ]] 

[[ 0.14498344 -1.38157278]
 [-0.08413389 -0.49114499]]


# **np.array_split(arr,split_parts)**


*   Allows you to split an array into unequal parts without requiring exact divisibility.




In [ ]:
arr1=np.random.randn(5,2)
print(arr1,"\n")
arr2=np.array_split(arr1,3)
print(arr2)

[[-1.17371687 -1.54749074]
 [-0.01755694  0.35105934]
 [ 0.59415456  0.10543321]
 [-0.36867484 -0.05443055]
 [-0.84411155 -1.04472681]] 

[array([[-1.17371687, -1.54749074],
       [-0.01755694,  0.35105934]]), array([[ 0.59415456,  0.10543321],
       [-0.36867484, -0.05443055]]), array([[-0.84411155, -1.04472681]])]


## **row_concatenation (Method 2)refer method 1 in numpy folder**



*   np.r_->short form of row concatenaion ,it combines the array in row-wise
* np.concatenate((arr1,arr2),axis=0/1)



In [ ]:
arr=np.arange(6)
print(arr)
arr1=arr.reshape(3,2)
print("array 1 ",arr1,"\n")
arr2=arr.reshape(3,2)
print("array 2 ",arr2,"\n")


[0 1 2 3 4 5]
array 1  [[0 1]
 [2 3]
 [4 5]] 

array 2  [[0 1]
 [2 3]
 [4 5]] 



In [ ]:
row_con=np.r_[arr1,arr2]
print("One dimension array : ",row_con,"\n")
row2_con=np.r_[[arr1,arr2]]
print("Two dimension array : ",row2_con)

One dimension array :  [[0 1]
 [2 3]
 [4 5]
 [0 1]
 [2 3]
 [4 5]] 

Two dimension array :  [[[0 1]
  [2 3]
  [4 5]]

 [[0 1]
  [2 3]
  [4 5]]]


### **Column contenation(Method 2)**

In [ ]:
col_conc=np.c_[arr1,arr2]
print(col_conc)

[[0 1 0 1]
 [2 3 2 3]
 [4 5 4 5]]


### **Repeating(arr.repeat(no.of times)) and replicating(arr.tile(no.of time))**

*   These two methods helps in array manipulation of various operation (add,sub..)like broadcasting,reshaping,transformation and so on..

*   Repeat->function helps to **repeat each elements in the array**.







In [ ]:
arr=np.arange(3)
arr.repeat(3) #repeats every element 3 times

array([0, 0, 0, 1, 1, 1, 2, 2, 2])

In [ ]:
arr.repeat([2,3,4]) #each element in the array is repeated different times
#the no.of repeated elements should be matched to the size of elements mentioned in arange function

array([0, 0, 1, 1, 1, 2, 2, 2, 2])

## **Multi-dimensional array repeatation on specific axis**

*    If no axis is passed, the array will be flattened first




In [ ]:
m_arr=np.random.randn(2,2)
m_arr.repeat(2,axis=0)

array([[ 0.15870215, -0.53760236],
       [ 0.15870215, -0.53760236],
       [ 0.54676747, -1.51747421],
       [ 0.54676747, -1.51747421]])

In [ ]:
m_arr.repeat([1,2],axis=0)

array([[ 0.15870215, -0.53760236],
       [ 0.54676747, -1.51747421],
       [ 0.54676747, -1.51747421]])

In [ ]:
m_arr.repeat(2,axis=1)

array([[ 0.15870215,  0.15870215, -0.53760236, -0.53760236],
       [ 0.54676747,  0.54676747, -1.51747421, -1.51747421]])

### **Replicate->(np.tile(arr,no.of times repeated))**
* The **entire array structure is repeated rather** than each element.

*   Second argument is how many times the array has to repeat it usually repeated in row-by-row wise
*   np.title(arr,**(no.of times_row_repeated,no_of_times_column_repeated)**)



In [ ]:
m_arr
np.tile(m_arr,2)

array([[ 0.15870215, -0.53760236,  0.15870215, -0.53760236],
       [ 0.54676747, -1.51747421,  0.54676747, -1.51747421]])

In [ ]:
np.tile(m_arr,(2,1))

array([[ 0.15870215, -0.53760236],
       [ 0.54676747, -1.51747421],
       [ 0.15870215, -0.53760236],
       [ 0.54676747, -1.51747421]])

In [ ]:
import numpy as np
arr=np.arange(10)
print(np.sum(arr))

45


In [ ]:
np.add.reduce(arr)

45

## **Setting Array Values by Broadcasting**

*  Creating 2D array here and initializing the new values




In [ ]:
import numpy as np
arr=np.zeros((4, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr[1:3]=5
print(arr)

[[1.28 1.28 1.28]
 [5.   5.   5.  ]
 [5.   5.   5.  ]
 [1.6  1.6  1.6 ]]


Converting 1D array into 2D array

*The arr should have a compatible shape

In [ ]:
col = np.array([1.28, -0.42, 0.44, 1.6])
print(col.shape)  #the shape of this array is (4,) because it has 4 elements only and it is a 1D array
arr[:] = col[:, np.newaxis]  #convert this 1D array into a 2D array with 4 rows and 1 column
#col[:]->indicates all elements in the array
#np.newaxis->adds a new axis converting the 1D array into column vector
arr

(4,)


array([[ 1.28,  1.28,  1.28],
       [-0.42, -0.42, -0.42],
       [ 0.44,  0.44,  0.44],
       [ 1.6 ,  1.6 ,  1.6 ]])

**Ufunctions advanced**

In [ ]:
u_arr=np.arange(10)
np.add.reduce(u_arr) #which is equal to the function arr.sum()


45

In [ ]:
arr = np.random.randn(5, 5)
arr[::2].sort(1) #sorts the elements in column wise
arr[:, :-1] < arr[:, 1:]


array([[ True,  True,  True,  True],
       [ True, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [ ]:
#uniary functions
np.logical_and.reduce(arr[:, :-1] < arr[:, 1:], axis=1)


array([ True, False,  True, False,  True])

### **Custom ufunc**

*   Can be created by **two ways**
*   Using frompyfunc(func,no.of inputs,no.of output the function returns) and numpy.vectorize()



In [ ]:
import numpy as np
def add_elements(x,y):
  return x+y
add_them=np.frompyfunc(add_elements,2,1) #converts python function to ufunc
print(add_them(np.arange(8),np.arange(8)))
#output->process [0+0 1+1 2+2 3+3 ......]


[0 2 4 6 8 10 12 14]


In [ ]:
def circle_area(radius):
  return np.pi*radius**2
circle_area=np.vectorize(circle_area)
radius_values=np.array([1,2,3])
areas=circle_area(radius_values)
print(areas)


[ 3.14159265 12.56637061 28.27433388]


### **Sort advance**

*   numpy.sort creates **new copy of the array** of an array




In [ ]:
sort_arr = np.random.randn(6)
sort_arr.sort()
print(sort_arr)

[-2.481224   -1.21378851 -0.82967433 -0.54680494  0.24495197  1.75746393]


In [ ]:
two_arr = np.random.randn(3, 5)
two_arr

array([[ 0.51102788, -0.93141214, -1.02724575, -0.00349055,  0.48604535],
       [-1.01192571,  1.31591553, -0.51927641, -0.58581743, -0.21504692],
       [ 0.37388391, -0.14540735, -0.05006114,  0.43607381,  1.93408715]])

In [ ]:
two_arr[:, 0].sort()
two_arr

array([[-1.01192571, -0.93141214, -1.02724575, -0.00349055,  0.48604535],
       [ 0.37388391,  1.31591553, -0.51927641, -0.58581743, -0.21504692],
       [ 0.51102788, -0.14540735, -0.05006114,  0.43607381,  1.93408715]])

In [ ]:
two_arr.sort(axis=1) #sort by column wise
two_arr

#reverse the array
arr[::-1]

array([-0.14754093,  0.96114399, -0.60991454, -1.62178211,  1.69639886])

### **np.sort()**

In [ ]:
arr = np.random.randn(5)
arr

array([ 1.69639886, -1.62178211, -0.60991454,  0.96114399, -0.14754093])

In [ ]:
np.sort(arr)

array([-1.62178211, -0.60991454, -0.14754093,  0.96114399,  1.69639886])

### **Indirect Sorts: argsort and lexsort**

*   argsort -> sort a **single array** or specific rows or columns of a multi-dimension array
*   lexaort -> sort on **multiple array**

*   It sorts based on the order of the keys(arrays), where the last key(last given array) in the input is the primary key and earlier keys are used for tie-breaking(i.e when same value found in both arrays it sorts by tie-breaking array i.e the previous array)






In [ ]:
values=np.array([5, 0, 1, 3, 2])
indexer=values.argsort() #returns the index of values that to be sorted
indexer

array([1, 2, 4, 3, 0])

In [ ]:
values[indexer] #using the index returned from indexer and using it to sort


array([0, 1, 2, 3, 5])

In [ ]:
arr = np.random.randn(3, 5)
print("Original arrar : ",arr,"\n")
arr[0]=values
print("Sorted array : ",arr)

Original arrar :  [[ 0.10127586  0.38309955 -0.13075126  0.93761847  0.13136614]
 [-1.29978637  0.26096373  0.56402315 -0.47327777  3.2223188 ]
 [ 0.50305431  0.80563912  0.7260217  -0.01448171 -1.24567663]] 

Sorted array :  [[ 5.          0.          1.          3.          2.        ]
 [-1.29978637  0.26096373  0.56402315 -0.47327777  3.2223188 ]
 [ 0.50305431  0.80563912  0.7260217  -0.01448171 -1.24567663]]


In [ ]:
arr[:, arr[0].argsort()]


array([[ 0.        ,  1.        ,  2.        ,  3.        ,  5.        ],
       [ 0.26096373,  0.56402315,  3.2223188 , -0.47327777, -1.29978637],
       [ 0.80563912,  0.7260217 , -1.24567663, -0.01448171,  0.50305431]])

In [ ]:
first_name = np.array(['Bob', 'Jane', 'Steve', 'Bill', 'Barbara'])
last_name = np.array(['Jones', 'Arnold', 'Arnold', 'Jones', 'Walters'])
sorter=np.lexsort((first_name,last_name))
#First -> sorts by last_name (bcz it is the last passed array) then returns the index
#if same values in both arrays then it sorts by first_name
sorted_name=list(zip(last_name[sorter],first_name[sorter]))
sorted_name
#the zip function always returns iterator like this '<zip at 0x7d80ed42ea00>'
#to get values you should convert it into list or another collection type
#it displays combination of first and last name

[('Arnold', 'Jane'),
 ('Arnold', 'Steve'),
 ('Jones', 'Bill'),
 ('Jones', 'Bob'),
 ('Walters', 'Barbara')]

### **Structured Array**

*   In numpy "array" is homogeneous(handles same data type well).
*   It also handles heterogeneous data but not efficient that much based on below example the int type is type casted into string it is not useful for complex(consists of different data types) data because you will loss the data.

To overcome this we use **Structured Arrays(fieldname, datatype, shape[optional])**

*   This allows you to store the data in its original format rather than type casting.
*   Useful in spreadsheet or database.
*   The each field can be accessed by their name how we access column tables.





In [ ]:
import numpy as np
a=np.array(['Riya',2])
a
#here 2->is type casted into string

array(['Riya', '2'], dtype='<U21')

### **Method 1 structured arrays**

In [ ]:
dtype = [('x', np.float64), ('y', np.int32)] #defines structural data type for array with two fields

sarr = np.array([(1.5, 6), (np.pi, -2)], dtype=dtype)
#creates a structured Numpy array with list of tuples, 1.5 -> x value ,6 ->y values
sarr

#if fieldname is empty string ' ' the field will be given a default name
#of the form f#, where # is the integer index of the field
#dtype=[('x', 'f4'), ('', 'i4'), ('z', 'i8')]


array([(1.5       ,  6), (3.14159265, -2)],
      dtype=[('x', '<f8'), ('y', '<i4')])

In [ ]:
sarr[0][1]

6

In [ ]:
np.max(sarr['x'])

3.141592653589793

### **Method 2 structure array**

In [ ]:
np.dtype({'names': ['col1', 'col2'], 'formats': ['i4', 'f4']})


dtype([('col1', '<i4'), ('col2', '<f4')])

## **Multi-dimensional structure array**

In [ ]:
dtype=[('x',np.int64,3),('y',np.int32)]
#Field name ->x , data type -> int , shape -> 3 (which holds 3 elements in the list)
#('y',np.int32) -> it does not consists of shape it only has one value

arr=np.zeros(4,dtype=dtype)
arr

array([([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0), ([0, 0, 0], 0)],
      dtype=[('x', '<i8', (3,)), ('y', '<i4')])

In [ ]:
arr[0]['x']

array([0, 0, 0])

### **Nested dtypes**

In [ ]:
dtype=[('x',[('a','f8'),('b','f4')]),('y',np.int32)]
data=np.array([((1,2),5),((4,6),20)],dtype=dtype)
data['x']

array([(1., 2.), (4., 6.)], dtype=[('a', '<f8'), ('b', '<f4')])

In [ ]:
data['y']

array([ 5, 20], dtype=int32)

In [ ]:
data['x']['a']

array([1., 4.])

### **numpy.searchsorted**

*   Performs binary search on a sorted array
*   returning the location in the array where the value would need to be inserted



In [1]:
import numpy as np
arr=np.array([0, 1, 7, 12, 15])
arr.searchsorted(9) #returns the index in which the new value has to inserted

3

In [2]:
arr.searchsorted([0, 8, 11, 16])

array([0, 3, 3, 5])